db_host: "{{ vault_db_host }}"
db_port: "{{ vault_db_port }}"
db_name: "{{ vault_db_name }}"
db_user: "{{ vault_db_user }}"
db_password: "{{ vault_db_password }}"
secret_key_base: "{{ vault_secret_key_base }}"
